CREATE TABLE JOBS(
ID INT PRIMARY KEY IDENTITY,
TITLE VARCHAR(30) NOT NULL)
CREATE TABLE SELLERS(
ID INT PRIMARY KEY IDENTITY,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
ID_JOB INT NOT NULL
CONSTRAINT JOB_KEY FOREIGN KEY (ID_JOB) REFERENCES JOBS(ID))
CREATE TABLE MARKS(
ID INT PRIMARY KEY IDENTITY,
TITLE VARCHAR(30) NOT NULL)
CREATE TABLE ITEM_TYPES(
ID INT PRIMARY KEY IDENTITY,
TITLE VARCHAR(30) NOT NULL)
CREATE TABLE CURRENCY(
ID INT PRIMARY KEY IDENTITY,
VALUTA VARCHAR(30) NOT NULL,
PRICE DECIMAL(10,2) NOT NULL CHECK (PRICE > 0))
CREATE TABLE ITEMS(
ID INT PRIMARY KEY IDENTITY,
FEATURE VARCHAR(120) NOT NULL,
STOCK_AMOUNT INT NOT NULL CHECK(STOCK_AMOUNT >= 0),
ID_PRICE INT NOT NULL
CONSTRAINT PRICE_KEY FOREIGN KEY(ID_PRICE) REFERENCES CURRENCY(ID),
PRICE_YO DECIMAL(10,2) NOT NULL CHECK(PRICE_YO > 0),
ID_MARK INT NOT NULL
CONSTRAINT MARK_KEY FOREIGN KEY (ID_MARK) REFERENCES MARKS(ID),
ID_TYPE INT NOT NULL
CONSTRAINT TYPE_KEY FOREIGN KEY (ID_TYPE) REFERENCES ITEM_TYPES(ID))
CREATE TABLE SALES(
ID_SELLER INT NOT NULL
CONSTRAINT SELLER_KEY FOREIGN KEY (ID_SELLER) REFERENCES SELLERS(ID),
DATE_SALE DATE NOT NULL CHECK (DATE_SALE >= '2000' AND DATE_SALE <= GETDATE()),
ID_ITEM INT NOT NULL
CONSTRAINT ITEM_KEY FOREIGN KEY (ID_ITEM) REFERENCES ITEMS(ID),
AMOUNT INT NOT NULL CHECK (AMOUNT > 0))
