CREATE PROC SELLER_DAY
@SELLER VARCHAR(30),
@DATE DATE
AS
IF EXISTS(SELECT 'TRUE' FROM SALES
INNER JOIN SELLERS ON SALES.ID_SELLER=SELLERS.ID
WHERE SELLERS.LASTNAME = @SELLER AND DATE_SALE=@DATE)
BEGIN
SELECT SELLERS.FIRSTNAME, SELLERS.LASTNAME, AMOUNT FROM SALES
INNER JOIN SELLERS ON SALES.ID_SELLER=SELLERS.ID
WHERE SELLERS.LASTNAME = @SELLER AND DATE_SALE=@DATE
END
ELSE
BEGIN
PRINT 'DOES NOT EXIST'
END
