CREATE TRIGGER FILM_DELETE ON FILMS
INSTEAD OF DELETE
AS
DECLARE @ID INT
SELECT @ID=ID FROM FILMS
IF EXISTS (SELECT 'TRUE' FROM FILMS_ACTORS WHERE ID_FILM=@ID)
BEGIN
DELETE FROM FILMS_ACTORS WHERE ID_FILM=@ID
END