CREATE VIEW ITEMS_LIST
AS SELECT ITEMS.ID, ITEMS.FEATURE, ITEMS.STOCK_AMOUNT, CURRENCY.PRICE*PRICE_YO AS PRICE, MARKS.TITLE AS MARK,
ITEM_TYPES.TITLE AS TP FROM ITEMS
INNER JOIN CURRENCY ON ITEMS.ID_PRICE=CURRENCY.ID
INNER JOIN MARKS ON ITEMS.ID_MARK=MARKS.ID
INNER JOIN ITEM_TYPES ON ITEMS.ID_TYPE=ITEM_TYPES.ID